# ArgoCDの管理画面をノードの30000ポートで公開
apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
